class Hub:
    def write(self):
        print("                                                      ____________________________________________________")
        print("                                                    /                                                      \\")
        print("                                                  /                                                          \\")
        print("                                                /                                                              \\")
        print("                                              /                                                                  \\")
        print("                                            /                                                                      \\")
        print("                                          /                                                                          \\")
        print("                                        /                                                                              \\")
        print("                                      /                                                                                  \\")
        print("                                    /                                                                                      \\")
        print("                                  /                                                                                          \\")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                |                                                                                              |")
        print("                                  \\                                                                                          /")
        print("                                    \\                                                                                      /")
        print("                                      \\                                                                                  /")
        print("                                        \\                                                                              /")
        print("                                          \\                                                                          /")
        print("                                            \\                                                                      /")
        print("                                              \\                                                                  /")
        print("                                                \\                                                              /")
        print("                                                  \\                                                          /")
        print("                                                    \\                                                      /")
        print("                                                      \\__________________________________________________/")
map = Hub()
map.write()