class Hub:
    def write(self):
        print("                                                      ____________________________________________________")
        print("                                                    /           /                               \\         \\")
        print("                                                  /     F     /                                   \\    W    \\")
        print("                                                /___________/                                       \\_________\\")
        print("                                              /                                                                  \\")
        print("                                            /                                                                      \\")
        print("                                          /                                                                          \\")
        print("                                        /                                                                              \\")
        print("                                      /                                                                                  \\")
        print("                                    /  |                                                                                 | \\")
        print("                                  /    |                                                                                 |   \\")
        print("                                |      |                                                                                 |    |")
        print("                                |      |                                                                                 |     |")
        print("                                |      |                                                                                 |     |")
        print("                                |      |                                                                                 |     |")
        print("                                |  A   |                                                                                 |  W  |")
        print("                                |  r   |                                                                                 |  p  |")
        print("                                |      |                                                                                 |     |")
        print("                                |      |                                                                                 |     |")
        print("                                |      |                                                                                 |     |")
        print("                                |      |                                                                                 |     |")
        print("                                  \\   |                                                                                 |    /")
        print("                                    \\ |                                                                                 |  /")
        print("                                      \\                                                                                  /")
        print("                                        \\                                                                              /")
        print("                                          \\                                                                          /")
        print("                                            \\                                                                      /")
        print("                                              \\                                                                  /")
        print("                                                \\_____________                                     ____________/")
        print("                                                  \\           \\                                  /          /")
        print("                                                    \\    E      \\                              /    A     /")
        print("                                                      \\___________\\__________________________/__________/")
map = Hub()
map.write()